
name: Build

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/**'
      - 'CMakeLists.txt'
      - 'ci/**'
      - 'cmake/**'
      - 'openvdb/**'
      - 'openvdb_houdini/**'

jobs:
  testabi7:
    runs-on: ubuntu-16.04
    container:
      image: aswf/ci-openvdb:2020
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./ci/build.sh clang++ Release 7 ON None
    - name: test
      run: cd build && ctest -V

  testhou180:
    runs-on: ubuntu-16.04
    container:
      image: aswf/ci-base:2019
    steps:
    - uses: actions/checkout@v2
    - name: secret
      run: |
          if [ "$HOUPASS" == "" ]; then
            echo "HOUPASS GitHub Action Secret needs to be set to test Houdini builds, skipping $HOUPASS"
            exit 0
          fi
      env:
        HOUPASS: ${{ secrets.HOUPASS }}
    - name: houdini
      run: |
          if [ "$HOUPASS" != "" ]; then
            ./ci/install_houdini.sh 18.0 "$HOUPASS"
          fi
      env:
        HOUPASS: ${{ secrets.HOUPASS }}
    - name: build
      run: |
        if [ "$HOUPASS" != "" ]; then
          ./ci/build_houdini.sh clang++ Release ON
        fi
      env:
        HOUPASS: ${{ secrets.HOUPASS }}

  testhou175:
    runs-on: ubuntu-16.04
    container:
      image: aswf/ci-base:2018
    steps:
    - uses: actions/checkout@v2
    - name: secret
      run: |
          if [ "$HOUPASS" == "" ]; then
            echo "HOUPASS GitHub Action Secret needs to be set to test Houdini builds"
            exit 1
          fi
      env:
        HOUPASS: ${{ secrets.HOUPASS }}
    - name: houdini
      run: ./ci/install_houdini.sh 17.5 ${{ secrets.HOUPASS }}
    - name: build
      run: ./ci/build_houdini.sh clang++ Release ON
