
name: Build

on:
  push:
    branches:
      - *
  pull_request:
    branches-ignore:
      - master

jobs:
  testabi7:
    runs-on: ubuntu-16.04
    container:
      image: aswf/ci-openvdb:2020
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./ci/build.sh clang++ Release 7 ON None
    - name: test
      run: cd build && ctest -V
