
name: Build

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/**'
      - 'CMakeLists.txt'
      - 'ci/**'
      - 'cmake/**'
      - 'openvdb/**'
      - 'openvdb_houdini/**'

jobs:
  testabi7:
    runs-on: ubuntu-16.04
    container:
      image: aswf/ci-openvdb:2020
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./ci/build.sh clang++ Release 7 ON None
    - name: test
      run: cd build && ctest -V

  testhou180:
    runs-on: ubuntu-16.04
    container:
      image: aswf/ci-base:2019
    steps:
    - uses: actions/checkout@v2
    - name: houdini
      run: |
          if [ "$HOUPASS" == "" ]; then
            echo EMPTY
          fi
          if [ "$HOUPASS" != "" ]; then
            echo NOTEMPTY
          fi
          ./ci/install_houdini.sh 18.0 "$HOUPASS"
      env:
        HOUPASS: ${{ secrets.HOUPASS }}
    - name: build
      run: ./ci/build_houdini.sh clang++ Release ON
