
name: Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'doc/*'
      - 'openvdb/*'
      - 'openvdb_houdini/*'

jobs:
  doxygen:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: ./ci/install_doxygen.sh
    - name: build
      run: ./ci/build_doxygen.sh
